### PR TITLE
update shutdown and restart

### PR DESCRIPTION
**Pull request by DrDecagon**
updated shutdown command to match changes to kill_processes.sh

### CODE REVIEW

**Comment by adangert** [comment]
Thanks for the PR, should it be -9 rather than -3? I couldn't find anything online for what -3 does

**Comment by DrDecagon** [comment]
-3 is -QUIT.  It is less aggressive than -9 aka -KILL but more aggressive then plain -15.  It allows a core dump first before ending and can be trapped if there is a good reason.  I suppose -2 might be better.  I wasn't sure exactly what the program might be doing or what I could break if I went with -9.  Maybe it is not saving anything.

https://www.linux.org/threads/kill-commands-and-signals.8881/
Here are the relevant bits from this link:

(-15) SIGTERM -   This signal requests a process to stop running. This signal can be ignored. The process is given time to gracefully shutdown. When a program gracefully shuts down, that means it is given time to save its progress and release resources. (This is the standard kill command without modifiers.)
(-2) SIGINT - This signal is the same as pressing ctrl-c. The process is interrupted and stopped. However, the process can ignore this signal. (This is basically what we want)
(-3) SIGQUIT - This is like SIGINT with the ability to make the process produce a core dump. (Can be trapped for debugging)
(-9) SIGKILL - The SIGKILL signal forces the process to stop executing immediately. The program cannot ignore this signal. This process does not get to clean-up either.

**Comment by DrDecagon** [comment]
For instance, in my kill_processes.sh script, I left your original kill command to let the program shutdown gracefully, then waited a couple seconds and then ran kill -3 to try to force it was stuck.

**Comment by adangert** [comment]
Thanks for the info, that's very helpful! Joustmania shouldn't be doing anything important like saving to files so killing it outright should generally be ok.

**Pull request merged**
